// This file is generated by scripts/import-proof-yourself-csv.mjs.
// Do not edit manually.

export interface ImportedSkillSeed {
  key: string;
  title: string;
  aliases: string[];
  slots: number[];
  sourceTitles: string[];
  status: string;
  completedSessions: number;
  sourceStartDates: string[];
}

export const IMPORTED_SKILLS_IMPORTED_AT = "2026-03-06T15:21:36.168Z";

export const IMPORTED_SKILL_SEEDS: ImportedSkillSeed[] = [
  {
    "key": "chess",
    "title": "Chess",
    "aliases": [
      "Chess"
    ],
    "slots": [
      1
    ],
    "sourceTitles": [
      "Chess"
    ],
    "status": "In progress",
    "completedSessions": 0,
    "sourceStartDates": [
      "11/08/2025"
    ]
  },
  {
    "key": "bachata",
    "title": "Bachata",
    "aliases": [
      "Bachata"
    ],
    "slots": [
      4
    ],
    "sourceTitles": [
      "Bachata"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "philosophy",
    "title": "Philosophy",
    "aliases": [
      "Philosophy"
    ],
    "slots": [
      6
    ],
    "sourceTitles": [
      "Philosophy"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "ukulele",
    "title": "Ukulele",
    "aliases": [
      "Ukulele"
    ],
    "slots": [
      7
    ],
    "sourceTitles": [
      "Ukulele"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "spanish",
    "title": "Spanish",
    "aliases": [
      "Learn Spanish",
      "Spanish"
    ],
    "slots": [
      8,
      72
    ],
    "sourceTitles": [
      "Learn Spanish",
      "Spanish"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "japanese",
    "title": "Japanese",
    "aliases": [
      "Japanese"
    ],
    "slots": [
      9
    ],
    "sourceTitles": [
      "Japanese"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "publicspeaking",
    "title": "Public Speaking",
    "aliases": [
      "Public Speaking"
    ],
    "slots": [
      11
    ],
    "sourceTitles": [
      "Public Speaking"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "yoga",
    "title": "Yoga",
    "aliases": [
      "Yoga"
    ],
    "slots": [
      12
    ],
    "sourceTitles": [
      "Yoga"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "magictricks",
    "title": "Magic Tricks",
    "aliases": [
      "Magic Tricks"
    ],
    "slots": [
      13
    ],
    "sourceTitles": [
      "Magic Tricks"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "lockpicking",
    "title": "Lockpicking",
    "aliases": [
      "Lock Picking",
      "Lockpicking"
    ],
    "slots": [
      14,
      87
    ],
    "sourceTitles": [
      "Lock Picking",
      "Lockpicking"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "hackingfundamentals",
    "title": "Hacking Fundamentals",
    "aliases": [
      "Hacking",
      "Hacking Fundamentals"
    ],
    "slots": [
      15
    ],
    "sourceTitles": [
      "Hacking"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "medicine",
    "title": "Medicine",
    "aliases": [
      "Medicine",
      "Medizin"
    ],
    "slots": [
      17
    ],
    "sourceTitles": [
      "Medizin"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "charismaticcommunication",
    "title": "Charismatic Communication",
    "aliases": [
      "Charismatic Communication",
      "Rhetorik & Charismatic Communication"
    ],
    "slots": [
      19
    ],
    "sourceTitles": [
      "Rhetorik & Charismatic Communication"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "courage",
    "title": "Courage",
    "aliases": [
      "Courage"
    ],
    "slots": [
      20
    ],
    "sourceTitles": [
      "Courage"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "microeconomicschallenge",
    "title": "Microeconomics Challenge",
    "aliases": [
      "Microeconomics Challenge",
      "Microeconomics Challenge / Economics (Tyler Cowen)"
    ],
    "slots": [
      21
    ],
    "sourceTitles": [
      "Microeconomics Challenge / Economics (Tyler Cowen)"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "fullstackengineering",
    "title": "Full-Stack Engineering",
    "aliases": [
      "Full Stack Engineer",
      "Full-Stack Engineering"
    ],
    "slots": [
      22
    ],
    "sourceTitles": [
      "Full Stack Engineer"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "jumpingropeanddancing",
    "title": "Jumping Rope & Dancing",
    "aliases": [
      "Jumping Rope & Dancing"
    ],
    "slots": [
      23
    ],
    "sourceTitles": [
      "Jumping Rope & Dancing"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "essayandblogwriting",
    "title": "Essay and Blog Writing",
    "aliases": [
      "Essay and Blog Writing",
      "Schreiben (z. B. Fachartikel, Blogs)"
    ],
    "slots": [
      24
    ],
    "sourceTitles": [
      "Schreiben (z. B. Fachartikel, Blogs)"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "digitalart",
    "title": "Digital Art",
    "aliases": [
      "Digital Art"
    ],
    "slots": [
      25
    ],
    "sourceTitles": [
      "Digital Art"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "filmmakingandvideoediting",
    "title": "Filmmaking and Video Editing",
    "aliases": [
      "Filmen und Video-Editing",
      "Filmmaking and Video Editing"
    ],
    "slots": [
      26
    ],
    "sourceTitles": [
      "Filmen und Video-Editing"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "3dprinting",
    "title": "3D Printing",
    "aliases": [
      "3D Printing",
      "3D-Druck"
    ],
    "slots": [
      27
    ],
    "sourceTitles": [
      "3D-Druck"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "standupcomedy",
    "title": "Stand-Up Comedy",
    "aliases": [
      "Stand-Up Comedy",
      "Stand-up-Comedy"
    ],
    "slots": [
      28
    ],
    "sourceTitles": [
      "Stand-up-Comedy"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "digitalanimation",
    "title": "Digital Animation",
    "aliases": [
      "Digital Animation",
      "Digitale Animation"
    ],
    "slots": [
      29
    ],
    "sourceTitles": [
      "Digitale Animation"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "spokenwordperformance",
    "title": "Spoken Word Performance",
    "aliases": [
      "Spoken Word",
      "Spoken Word Performance"
    ],
    "slots": [
      30
    ],
    "sourceTitles": [
      "Spoken Word"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "marketing",
    "title": "Marketing",
    "aliases": [
      "Marketing"
    ],
    "slots": [
      31
    ],
    "sourceTitles": [
      "Marketing"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "entrepreneurshipandstartupbuilding",
    "title": "Entrepreneurship and Startup Building",
    "aliases": [
      "Entrepreneurship and Startup Building",
      "Unternehmertum / Startup-Gründung"
    ],
    "slots": [
      32
    ],
    "sourceTitles": [
      "Unternehmertum / Startup-Gründung"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "equitytrading",
    "title": "Equity Trading",
    "aliases": [
      "Aktienhandel",
      "Equity Trading"
    ],
    "slots": [
      33
    ],
    "sourceTitles": [
      "Aktienhandel"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "scientificresearch",
    "title": "Scientific Research",
    "aliases": [
      "Scientific Research",
      "Wissenschaftliche Forschung"
    ],
    "slots": [
      34
    ],
    "sourceTitles": [
      "Wissenschaftliche Forschung"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "cybersecuritypractice",
    "title": "Cybersecurity Practice",
    "aliases": [
      "Cybersecurity Practice",
      "Hacking / Cybersecurity"
    ],
    "slots": [
      35
    ],
    "sourceTitles": [
      "Hacking / Cybersecurity"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "vrardevelopment",
    "title": "VR/AR Development",
    "aliases": [
      "Virtual Reality / Augmented Reality Entwicklung",
      "VR/AR Development"
    ],
    "slots": [
      36
    ],
    "sourceTitles": [
      "Virtual Reality / Augmented Reality Entwicklung"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "bjjandboxing",
    "title": "BJJ and Boxing",
    "aliases": [
      "BJJ / Boxen",
      "BJJ and Boxing"
    ],
    "slots": [
      37
    ],
    "sourceTitles": [
      "BJJ / Boxen"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "tennis",
    "title": "Tennis",
    "aliases": [
      "Tennis"
    ],
    "slots": [
      38
    ],
    "sourceTitles": [
      "Tennis"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "tischtennis",
    "title": "Tischtennis",
    "aliases": [
      "Tischtennis"
    ],
    "slots": [
      39
    ],
    "sourceTitles": [
      "Tischtennis"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "surfing",
    "title": "Surfing",
    "aliases": [
      "Surfen",
      "Surfing"
    ],
    "slots": [
      41
    ],
    "sourceTitles": [
      "Surfen"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "sailingandsailinglicense",
    "title": "Sailing and Sailing License",
    "aliases": [
      "Sailing and Sailing License",
      "Segeln & Segelschein"
    ],
    "slots": [
      42
    ],
    "sourceTitles": [
      "Segeln & Segelschein"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "volleyball",
    "title": "Volleyball",
    "aliases": [
      "Volleyball"
    ],
    "slots": [
      43
    ],
    "sourceTitles": [
      "Volleyball"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "armwrestling",
    "title": "Armwrestling",
    "aliases": [
      "Armwrestling"
    ],
    "slots": [
      44
    ],
    "sourceTitles": [
      "Armwrestling"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "survivalskills",
    "title": "Survival Skills",
    "aliases": [
      "Survival Skills"
    ],
    "slots": [
      46
    ],
    "sourceTitles": [
      "Survival Skills"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "classicalartandmusic",
    "title": "Classical Art and Music",
    "aliases": [
      "Classical Art and Music",
      "Culture Classic Art / Music"
    ],
    "slots": [
      48
    ],
    "sourceTitles": [
      "Culture Classic Art / Music"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "gamedevelopment",
    "title": "Game Development",
    "aliases": [
      "Game Development"
    ],
    "slots": [
      49
    ],
    "sourceTitles": [
      "Game Development"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "classicliterature",
    "title": "Classic Literature",
    "aliases": [
      "Classic Literature"
    ],
    "slots": [
      50
    ],
    "sourceTitles": [
      "Classic Literature"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "debater",
    "title": "Debater",
    "aliases": [
      "Debater"
    ],
    "slots": [
      51
    ],
    "sourceTitles": [
      "Debater"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "shortstorywriting",
    "title": "Short Story Writing",
    "aliases": [
      "Short Story Writing",
      "Writing Shortstories"
    ],
    "slots": [
      52
    ],
    "sourceTitles": [
      "Writing Shortstories"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "presentationmastery",
    "title": "Presentation Mastery",
    "aliases": [
      "Mastering the Art of Presentation",
      "Presentation Mastery"
    ],
    "slots": [
      53
    ],
    "sourceTitles": [
      "Mastering the Art of Presentation"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "oncamerapresence",
    "title": "On-Camera Presence",
    "aliases": [
      "On-Camera Presence",
      "Talking to the Camera"
    ],
    "slots": [
      54
    ],
    "sourceTitles": [
      "Talking to the Camera"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "youtubecreation",
    "title": "YouTube Creation",
    "aliases": [
      "YouTube Creation",
      "YouTube Project"
    ],
    "slots": [
      55
    ],
    "sourceTitles": [
      "YouTube Project"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "socialmediagrowthexperiments",
    "title": "Social Media Growth Experiments",
    "aliases": [
      "Social Media Growth Experiments",
      "Try to Grow a Social Media Following (Instagram / Twitter)"
    ],
    "slots": [
      57
    ],
    "sourceTitles": [
      "Try to Grow a Social Media Following (Instagram / Twitter)"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "highimpactcommunication",
    "title": "High-Impact Communication",
    "aliases": [
      "High-Impact Communication",
      "Super Communicator"
    ],
    "slots": [
      58
    ],
    "sourceTitles": [
      "Super Communicator"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "buildyourfirstapp",
    "title": "Build Your First App",
    "aliases": [
      "Build Your First App"
    ],
    "slots": [
      58
    ],
    "sourceTitles": [
      "Build Your First App"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "socialaudiencegrowthsystems",
    "title": "Social Audience Growth Systems",
    "aliases": [
      "Grow on Social Media Project",
      "Social Audience Growth Systems"
    ],
    "slots": [
      59
    ],
    "sourceTitles": [
      "Grow on Social Media Project"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "gardening",
    "title": "Gardening",
    "aliases": [
      "Gardening"
    ],
    "slots": [
      60
    ],
    "sourceTitles": [
      "Gardening"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "sales",
    "title": "Sales",
    "aliases": [
      "Sales"
    ],
    "slots": [
      61
    ],
    "sourceTitles": [
      "Sales"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "dailywritingpractice",
    "title": "Daily Writing Practice",
    "aliases": [
      "Daily Writing Practice",
      "Writing"
    ],
    "slots": [
      62
    ],
    "sourceTitles": [
      "Writing"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "biology",
    "title": "Biology",
    "aliases": [
      "Biologie",
      "Biology"
    ],
    "slots": [
      64
    ],
    "sourceTitles": [
      "Biologie"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "chemistry",
    "title": "Chemistry",
    "aliases": [
      "Chemie",
      "Chemistry"
    ],
    "slots": [
      65
    ],
    "sourceTitles": [
      "Chemie"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "landscapedrawing",
    "title": "Landscape Drawing",
    "aliases": [
      "Landscape Drawing",
      "Learn to Draw Landscapes"
    ],
    "slots": [
      66
    ],
    "sourceTitles": [
      "Learn to Draw Landscapes"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "rhetoricalprecision",
    "title": "Rhetorical Precision",
    "aliases": [
      "Rhetorical Precision",
      "Rhetorik"
    ],
    "slots": [
      67
    ],
    "sourceTitles": [
      "Rhetorik"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "memorytechniques",
    "title": "Memory Techniques",
    "aliases": [
      "Memory Techniken (z. B. Kartendeck)",
      "Memory Techniques"
    ],
    "slots": [
      68,
      77
    ],
    "sourceTitles": [
      "Memory Techniken (z. B. Kartendeck)",
      "Memory Techniques"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "portraitdrawingchallenge",
    "title": "Portrait Drawing Challenge",
    "aliases": [
      "Portrait Challenge",
      "Portrait Drawing Challenge"
    ],
    "slots": [
      69
    ],
    "sourceTitles": [
      "Portrait Challenge"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "french",
    "title": "French",
    "aliases": [
      "French",
      "Learn French"
    ],
    "slots": [
      70
    ],
    "sourceTitles": [
      "Learn French"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "chinese",
    "title": "Chinese",
    "aliases": [
      "Chinese",
      "Learn Chinese"
    ],
    "slots": [
      71
    ],
    "sourceTitles": [
      "Learn Chinese"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "guitar",
    "title": "Guitar",
    "aliases": [
      "Gitarre",
      "Guitar"
    ],
    "slots": [
      73
    ],
    "sourceTitles": [
      "Gitarre"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "drums",
    "title": "Drums",
    "aliases": [
      "Drums",
      "Schlagzeug"
    ],
    "slots": [
      74
    ],
    "sourceTitles": [
      "Schlagzeug"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "piano",
    "title": "Piano",
    "aliases": [
      "Klavier",
      "Piano"
    ],
    "slots": [
      75
    ],
    "sourceTitles": [
      "Klavier"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "quantitativefinance",
    "title": "Quantitative Finance",
    "aliases": [
      "Quant. Finance",
      "Quantitative Finance"
    ],
    "slots": [
      78
    ],
    "sourceTitles": [
      "Quant. Finance"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "singing",
    "title": "Singing",
    "aliases": [
      "Singing"
    ],
    "slots": [
      79
    ],
    "sourceTitles": [
      "Singing"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "physics101explainers",
    "title": "Physics 101 Explainers",
    "aliases": [
      "MASTER Explainer for Physics 101",
      "Physics 101 Explainers"
    ],
    "slots": [
      80
    ],
    "sourceTitles": [
      "MASTER Explainer for Physics 101"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "statistics101",
    "title": "Statistics 101",
    "aliases": [
      "Statistics 101"
    ],
    "slots": [
      81
    ],
    "sourceTitles": [
      "Statistics 101"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "balanceslackline",
    "title": "Balance / Slackline",
    "aliases": [
      "Balance / Slackline"
    ],
    "slots": [
      82
    ],
    "sourceTitles": [
      "Balance / Slackline"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "dexteritygames",
    "title": "Dexterity Games",
    "aliases": [
      "Dexterity Games",
      "Geschicklichkeitsspiele"
    ],
    "slots": [
      83
    ],
    "sourceTitles": [
      "Geschicklichkeitsspiele"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "puzzles",
    "title": "Puzzles",
    "aliases": [
      "Puzzles",
      "Rätsel"
    ],
    "slots": [
      84
    ],
    "sourceTitles": [
      "Rätsel"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "baker",
    "title": "Baker",
    "aliases": [
      "Baker"
    ],
    "slots": [
      85
    ],
    "sourceTitles": [
      "Baker"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "cooking",
    "title": "Cooking",
    "aliases": [
      "Cooking"
    ],
    "slots": [
      86
    ],
    "sourceTitles": [
      "Cooking"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  },
  {
    "key": "fencing",
    "title": "Fencing",
    "aliases": [
      "Fechten",
      "Fencing"
    ],
    "slots": [
      88
    ],
    "sourceTitles": [
      "Fechten"
    ],
    "status": "Not started",
    "completedSessions": 0,
    "sourceStartDates": []
  }
];
